### ISSUE TITLE
LibriFox 1.0.2 xenial version crashes when starting

### ISSUE THREAD

**Issue by advocatux** [mjsir911/LibriFox#16]
When trying to start LibriFox in a xenial device, it crashes quickly.

These are the relevant application-click-librifox.mjsir911_cordova_1.0.2.log, unity8.log, and syslog bits https://paste.ubuntu.com/p/43wZvQR8Vm/

Thank you for your work!!

**Comment by AlexanderPlaza** [comment]
Attempting to run this app on Nexus 5 (hammerhead) running 16.04 RC 12. It now closes immediately after starting. If you require logs please let me know.

**Comment by mjsir911** [comment]
Hi All, Thanks for your interest in this project.

The version on the open-store should now be 16.04 compatible.

I mistakenly uploaded 15.04-only version and labelled it xenial & vivid.

Thank you for your submitted issue, could somebody (@advocatux @AlexanderPlaza) confirm this has been solved and close it?

**Comment by advocatux** [comment]
I can confirm the latest version for xenial (librifox.mjsir911_1.0.3_armhf.click) doesn't crash when starting now, so I'm closing this bug report.

Oh, I almost forgot to say thank you for your work !! :)
